# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Digital_Modernization_Azure_Lab(5c09efad-987e-4392-b86b-e27fddefe153)'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '/tets'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
